### ISSUE TITLE
Add default mix to dilutions

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#50]
I think we will always want a full (mixcode=2) mix after a dilution, so this can be added as a default step as part of a dilution. I think we ALSO want callbacks working, in case we want additional mixing or something.

Make sure you let Mark know when this is done so the inputs for the reactions are adjusted accordingly.

**Comment by harveymk** [comment]
Fixed? Need to test on robot first

**Comment by mphendricks** [comment]
This doesn't look like it's working yet. When I run a dilution in a test on the robot, it just goes on to the next transfer without doing a dilution.
