### ISSUE TITLE
Tip goes a little too deep when mixing full 15 mL tubes

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#52]
During mixing a 15/50 mL tube that's mostly full, the maximum depth the tip should go down is based on the length of the tip (so that we only submerge the tip and not the pipette itself). It seems like this is working, but it's going just a little too deep so it's just submerging past the tip/touching the pipette. I think 5 mm less deep/higher would solve the problem and then I can test again. Overall mixes are looking really good though!

**Comment by Hendricks-Laboratory** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/85696658/155025811-276e3b89-bdbd-4474-8b55-ba977d00fdd1.png">

If we change all of these 55s to 50s I think we'd probably be okay!

**Comment by Hendricks-Laboratory** [comment]
The tip is still going too far in. I think we need to change the 55 on line 459 to 50 and try that, but then we might need to adjust both to something even smaller (although the tips are 59-60mm long, so I don't know why the 55 isn't working)

**Comment by harveymk** [comment]
Did this change!

**Comment by mphendricks** [comment]
I'm going to leave this open until it's tested

**Comment by mphendricks** [comment]
This is just barely good enough, with surface tension it's not going above the tip, but with a different solution/temperature/luck, it probably would touch. Let's change both of these 50s to 48 and I think we'll be good!
