### ISSUE TITLE
Adjusting plot fonts/making sure labels aren't cut off

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#53]
On normal (not multi_kinetics) plots, the X and Y axes labels (Wavelength (nm) and Absorbance (a.u.) are slightly cut off on the edge of the figure.

Also, can we make axes labels and values the same size and make the square part of the plot smaller relative to the font size for the axis labels (i.e. bigger fonts)? I'm okay if we don't label every 0.1 a.u. or 100 nm, it could be labeled every 0.2 and 200 or whatever. As a reference, our normal figures use 16 pt font for all text (except legends) and a 2.5''x2.5'' box (or 32pt font and a 5''x5'' box). 

Let me know if you have questions about this.

![image](https://user-images.githubusercontent.com/85696658/154764942-627f9f08-0bd0-4cb3-a3cf-6886f8340c75.png)

**Comment by Hendricks-Laboratory** [comment]
The attached figure is an example of what our group's figures normally look like (not that this one only goes to 800 instead of 1000 nm).

**Comment by Hendricks-Laboratory** [comment]
![image](https://user-images.githubusercontent.com/85696658/154767144-a6e04cfb-5ef4-410b-bab6-105530b4f9e6.png)
This is an example of the cutoff axis labels.

**Comment by didwayg** [comment]
Fixed using matplotlib rcParams and updating autolayout to True.
