### ISSUE TITLE
2 mL tube aspirate/mix might be going too low

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#56]
When mixing at the lowest height of the 2mL tubes I don't see any volume coming up, which I think is because the tip is touching the bottom of the tube and not able to suck up any liquid. It doesn't seem to be crashing though, and it's possible the problem is with the aspirate volume or something, but that seems unlikely to me.

Here's the code at issue:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/85696658/155026163-f86c8d1c-915a-487f-893a-9d94a6712211.png">

**Comment by Hendricks-Laboratory** [comment]
I think maybe just increase the min_height to 4.5 or 5 mm and see how that goes?

Is it an issue that min_height is 4mm but our asp_height is self.height - 6, so if we ever tried to aspirate below the height_bottom_cylinder we'd have a negative height? I think think we ever do this though because of the dead volume, so maybe it doesn't matter.

**Comment by harveymk** [comment]
Fixed? need to test

**Comment by Hendricks-Laboratory** [comment]
I think the calibration fix undid this change--can we increase the MIN_HEIGHT on line ~566 to 6 mm and see how this goes?

**Comment by Hendricks-Laboratory** [comment]
Edited in main branch. Need to test.

**Comment by mphendricks** [comment]
I think we're good!
