### ISSUE TITLE
Build separate plotting input sheet/software

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#58]
Sometimes we might not realize (or just forget) that a certain combination of data would be useful to see on a plot together. Right now there isn't an easy way to go back to create new plots (that I'm aware of). We should create a separate piece of software that isn't used for running reactions--just for plotting. When run a user would input the name of the original sheet (e.g. MPH_test10), and then it would create an input sheet that looks like the normal one (including copying all of the product names over) except it only accepts plotting inputs. Then it would run and create the plots.

**Comment by kaplannp** [comment]
I agree. This is what I'd recommended at the beginning. I have some thoughts on how to do this that we should talk about before we start,  and probably best to avoid large changes to plotting software until we've built this out.
