### ISSUE TITLE
Clean up user accounts

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#60]
Before Noah & Max graduate, I'd like to clean up some of our accounts. Right now we have at least two lab emails (science.356.lab@gmail.com and science.356.lab.software@gmail.com [used for github--not sure if anything else]) and multiple different passwords being used for the different various things, including the SSH for the robot. I'd like to try to consolidate these as much as possible, and probably change the name of the GitHub account to Hendricks_Lab or something (in case we ever move labs or something, I'd prefer not to build up a public presence at science356lab).

Any other account/data management stuff either of you can think of that should be done before you leave?

**Comment by kaplannp** [comment]
ubuntu shell on laptop is updated to same password as laptop.
Robot ssh password is unchanged.
