### ISSUE TITLE
New way to deal with calibrations

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#62]
So I think I've figured out this issue with the 5.0.0 Opentrons software update messing up our calibrations. Prior to this calibrations were automatically saved in the Opentrons app (and I think that means stored somewhere on the robot) and I *think* they were automatically recalled when any protocol was run, whether through the app, Jupyter, or command line. It seems like deck and pipette calibrations will still be treated like this, but labware calibrations will not be handled automatically. I think this will allow more transparency in what's going on and hopefully improve the calibrations, which we've always had issues with, but it also means we need to update our code (everytime we calibrate something, I think). 

[example1.pdf](https://github.com/science356lab/OT2Control/files/8157461/example1.pdf)

The screenshot above is taken from the Opentrons app when setting up a protocol and now there's a link (see red arrow) that allows us to download the data from the calibrations. I think we're supposed to incorporate this into our code. Here's exactly what it provided for that protocol (plus my comments):
```
#command line SSH
from opentrons import protocol_api

metadata = {
    "apiLevel": "2.12"
}

def run(protocol: protocol_api.ProtocolContext):
    module_1 = protocol.load_module("temperatureModuleV2", location="3")
    
    labware_1 = protocol.load_labware("opentrons_1_trash_1100ml_fixed", location="12")
    labware_1.set_offset(x=0.00, y=0.00, z=0.00)
    
    labware_2 = protocol.load_labware("opentrons_96_tiprack_20ul", location="5")
    labware_2.set_offset(x=-0.50, y=1.50, z=-0.70)
    
    labware_3 = protocol.load_labware("opentrons_96_tiprack_300ul", location="9")
    labware_3.set_offset(x=0.00, y=0.00, z=0.00)
    #this labware wasn't used in this protocol so no calibration was made and therefore all of the values are 0. I bet we can use the same values as the other 300uL tip rack though.
    
    labware_4 = protocol.load_labware("opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical", location="2")
    labware_4.set_offset(x=-0.10, y=1.20, z=4.90)
    
    labware_5 = module_1.load_labware("opentrons_24_aluminumblock_generic_2ml_screwcap")
    labware_5.set_offset(x=0.30, y=2.50, z=-6.60)
    
    labware_6 = protocol.load_labware("opentrons_96_tiprack_300ul", location="8")
    labware_6.set_offset(x=0.30, y=0.50, z=-0.30)
    
    labware_7 = protocol.load_labware("opentrons_96_tiprack_20ul", location="6")
    labware_7.set_offset(x=0.00, y=0.00, z=0.00)
    #this labware wasn't used in this protocol so no calibration was made and therefore all of the values are 0. I bet we can use the same values as the other 20uL tip rack though.
    
    labware_8 = protocol.load_labware("plate_reader_4", location="4")
    labware_8.set_offset(x=-0.30, y=0.30, z=-0.90)
    
    labware_9 = protocol.load_labware("plate_reader_7", location="7")
    labware_9.set_offset(x=0.00, y=-0.10, z=-0.80)
    
    labware_10 = protocol.load_labware("opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical", location="1")
    labware_10.set_offset(x=-0.20, y=1.80, z=4.60)
```
-----
So I think it's the X.set_offset(x=?, y=?, z=?) lines that we need to add when we create the labware in our code. Technically these calibrations are supposed to be specific to the deck location, but my guess is that they are basically the same across the deck. I don't know if we want to hardcode these into the code or put them into the Google sheets so they can be edited there. Until these get added to the code I can't do much testing because things keep crashing.

**Comment by kaplannp** [comment]
Worked out a patch. Must manually code a dictionary to keep track of calibrations, and the robot will read in calibrations at runtime

**Comment by Hendricks-Laboratory** [comment]
It works!
