### ISSUE TITLE
touch tip can apply pressure to tube at end of aspirate

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#65]
The touch tip feature at the end of the aspirate cycle ends with the tip directly touching the tube at the edge closest to the door of the robot. The tip then pulls up before going off to its next destination. If the calibrations are off a little bit, it can apply pressure to the tube when it lifts up, potentially moving the tube or getting caught in the tube. Again, the calibrations were off enough before that this was never an issue, but now that the touch tip is working it's causing an issue. 

I think the solution is to do a move_to to the top center of the well before pulling the tip up. I think this might involve getting rid of the aspirate_cleanup function and just merge it into aspirate. Here's the code we're looking at:
[exaplme2.pdf](https://github.com/science356lab/OT2Control/files/8165341/exaplme2.pdf)

Here's some possible example code:

        if self.aspiratible_vol < vol:
            #if you can't raise error to show that you are empty
            raise EmptyReagent('cannot aspirate {:.3}uL from {} because it only has {:.3}uL'.format(vol,self.name,float(self.aspiratible_vol)), self.name)
        #set aspiration height
        pipette.well_bottom_clearance.aspirate = self.asp_height
        #aspirate(well_obj)
        pipette.aspirate(vol, lab_deck[self.deck_pos].get_well(self.loc))
        #update the vol of src
        self.update_vol(-vol)

        #here's the new stuff:

        #touch tip to remove drops from outside of tip
        pipette.touch_tip()
        #move tip *directly* to center of well/tube so it doesn't interact with the well/tube when it lifts up
        pipette.move_to(lab_deck[self.deck_pos].get_well(self.loc).top(), force_direct=True)

        #get rid of aspirate_cleanup function since it's only one touch_tip and we need all of the other variables for the move_to at the end of the touch_tip anyways
        #call cleanup
        #self._aspirate_cleanup(pipette)
'

**Comment by mphendricks** [comment]
Looks good!
