### ISSUE TITLE
add a third mix height for 2 mL tube mixing

### ISSUE THREAD

**Issue by Hendricks-Laboratory** [Hendricks-Laboratory/OT2Control#66]
On line 616 of the current version of the code we have: 
        heights = [self.MIN_HEIGHT, self.asp_height]

Instead, can we replace that with
     heights = np.linspace(self.MIN_HEIGHT, self.asp_height, 3)

which is basically the same as the 4 levels in the bigger tubes, but only three heights here (bottom, top, and average).

**Comment by mphendricks** [comment]
This appears to be working with the exception of callbacks. I've created a new issue for that, so I'm closing this.
